version: '3.4'

services:
  s3-proj:
    image: ${DOCKER_REGISTRY-}s3proj
    build:
      context: .
      dockerfile: s3-proj/Dockerfile

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1450:1433
    volumes:
      - mssqldata:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Gunnoe123
volumes:
      mssqldata:  
        external: true
        