name: postman-pull-request
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  Newman:
    runs-on: ubuntu-latest

    steps:
    - name: Newman Action
      uses: matt-ball/newman-action@v1.0.4
      with: 
        collection: https://raw.githubusercontent.com/Axelpieterman/s3-proj/main/tests/Article.postman_collection.json
       
        environment: https://raw.githubusercontent.com/Axelpieterman/s3-proj/main/tests/Gunnoe-env.json

