name: postman-pull-request
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  Newman:
    runs-on: ubuntu-latest

    steps:
    - name: Newman Action
      uses: matt-ball/newman-action@v1.0.4
      with: 
        collection: https://github.com/Axelpieterman/s3-proj/blob/main/tests/Article.postman_collection.json
        environment: https://github.com/Axelpieterman/s3-proj/blob/main/tests/Gunnoe-env.json

